# Form implementation generated from reading ui file 'task.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(730, 532)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(1470, 829))
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.calendarWidget_2 = QtWidgets.QCalendarWidget(parent=self.centralwidget)
        self.calendarWidget_2.setGeometry(QtCore.QRect(30, 20, 671, 361))
        self.calendarWidget_2.setStyleSheet("QCalendarWidget {\n"
"    background-color: #1e1e1e;\n"
"    color: #dcdcdc;\n"
"    border: 1px solid #444;\n"
"    selection-background-color: #00ff88;\n"
"}\n"
"\n"
"QCalendarWidget QAbstractItemView {\n"
"    background-color: #121212;\n"
"    selection-background-color: #00ff88;\n"
"    selection-color: black;\n"
"    gridline-color: #333;\n"
"    color: #dcdcdc;\n"
"}\n"
"\n"
"QCalendarWidget QWidget#qt_calendar_navigationbar {\n"
"    background-color: #2b2b2b;\n"
"    color: white;\n"
"}\n"
"\n"
"QToolButton {\n"
"    color: white;\n"
"    background: transparent;\n"
"    border: none;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.calendarWidget_2.setSelectionMode(QtWidgets.QCalendarWidget.SelectionMode.SingleSelection)
        self.calendarWidget_2.setHorizontalHeaderFormat(QtWidgets.QCalendarWidget.HorizontalHeaderFormat.ShortDayNames)
        self.calendarWidget_2.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.VerticalHeaderFormat.NoVerticalHeader)
        self.calendarWidget_2.setNavigationBarVisible(True)
        self.calendarWidget_2.setDateEditEnabled(False)
        self.calendarWidget_2.setObjectName("calendarWidget_2")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(510, 410, 191, 51))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: #5e4b8b;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 8px 20px;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #7a62b3;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #483370;\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(270, 410, 191, 51))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: #5e4b8b;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 8px 20px;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #7a62b3;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #483370;\n"
"}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(30, 410, 191, 51))
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: #5e4b8b;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 8px 20px;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #7a62b3;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #483370;\n"
"}\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 730, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_2.setText(_translate("MainWindow", "delete"))
        self.pushButton_3.setText(_translate("MainWindow", "edit"))
        self.pushButton_4.setText(_translate("MainWindow", "add"))
