# Form implementation generated from reading ui file 'task.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(764, 651)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(1470, 829))
        MainWindow.setStyleSheet("background-color: rgb(50, 50, 50);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.calendarWidget_2 = QtWidgets.QCalendarWidget(parent=self.centralwidget)
        self.calendarWidget_2.setGeometry(QtCore.QRect(50, 70, 671, 361))
        self.calendarWidget_2.setStyleSheet("QCalendarWidget {\n"
"    background-color: #1e1e1e;\n"
"    color: #dcdcdc;\n"
"    border: 1px solid #444;\n"
"    selection-background-color: #00ff88;\n"
"}\n"
"\n"
"QCalendarWidget QWidget#qt_calendar_navigationbar {\n"
"    background-color: #2b2b2b;\n"
"    color: white;\n"
"}\n"
"\n"
"QCalendarWidget QToolButton {\n"
"    color: white;\n"
"    background-color: #5e4b8b;\n"
"    font-weight: bold;\n"
"    font-size: 16px;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    margin: 2px;\n"
"}\n"
"\n"
"QCalendarWidget QToolButton::menu-indicator {\n"
"    image: none;  /* убираем стрелочку */\n"
"}\n"
"\n"
"QCalendarWidget QAbstractItemView {\n"
"    background-color: #121212;\n"
"    selection-background-color: #00ff88;\n"
"    selection-color: black;\n"
"    gridline-color: #333;\n"
"    color: #dcdcdc;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QCalendarWidget QHeaderView {\n"
"    background-color: #1e1e1e;\n"
"}\n"
"\n"
"QCalendarWidget QHeaderView::section {\n"
"    color: #bbbbbb;\n"
"    background-color: #1e1e1e;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    padding: 4px;\n"
"}\n"
"")
        self.calendarWidget_2.setSelectionMode(QtWidgets.QCalendarWidget.SelectionMode.SingleSelection)
        self.calendarWidget_2.setHorizontalHeaderFormat(QtWidgets.QCalendarWidget.HorizontalHeaderFormat.ShortDayNames)
        self.calendarWidget_2.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.VerticalHeaderFormat.NoVerticalHeader)
        self.calendarWidget_2.setNavigationBarVisible(True)
        self.calendarWidget_2.setDateEditEnabled(False)
        self.calendarWidget_2.setObjectName("calendarWidget_2")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(620, 10, 131, 41))
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color: #5e4b8b;\n"
"    color: white;\n"
"    border: 2px solid #3e2f5c; /* <–– добавлена граница */\n"
"    border-radius: 12px;\n"
"    padding: 8px 20px;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #7a62b3;\n"
"    border-color: #5a4691; /* можно поменять цвет при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #483370;\n"
"    border-color: #2f214f; /* можно поменять цвет при нажатии */\n"
"}\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-40, -5, 831, 61))
        self.label.setStyleSheet("background-color: #5e4b8b;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(50, 460, 671, 121))
        self.tableWidget.setStyleSheet("QTableWidget {\n"
"    background-color: #1e1e1e;\n"
"    color: #e0e0e0;\n"
"    gridline-color: #444;\n"
"    border: 1px solid #333;\n"
"    font-size: 14px;\n"
"    selection-background-color: #5e4b8b;\n"
"    selection-color: white;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #2b2b2b;\n"
"    color: #ffffff;\n"
"    font-weight: bold;\n"
"    padding: 5px;\n"
"    border: 1px solid #444;\n"
"}\n"
"\n"
"QTableWidget QTableCornerButton::section {\n"
"    background-color: #2b2b2b;\n"
"    border: 1px solid #444;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 4px;\n"
"    border: none;\n"
"}\n"
"")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.label.raise_()
        self.calendarWidget_2.raise_()
        self.pushButton_5.raise_()
        self.tableWidget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 764, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_5.setText(_translate("MainWindow", "Sign up"))
